# Generated by Django 4.2.6 on 2024-02-01 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOGIN', 'Вход'), ('LOGOUT', 'Выход'), ('FAILED', 'Неуспешная попытка входа')], max_length=6, verbose_name='Тип')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя')),
                ('user_pk', models.BigIntegerField(blank=True, null=True, verbose_name='Первичный ключ пользователя')),
                ('user_repr', models.TextField(blank=True, verbose_name='Отображение пользователя')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит аутентификации',
                'verbose_name_plural': 'Аудит аутентификации',
                'ordering': ['-timestamp'],
            },
        ),
    ]
