# Generated by Django 4.2.6 on 2023-12-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_advertisementfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='header',
        ),
    ]
