# Generated by Django 4.2.6 on 2023-12-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisementfile_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementfile',
            name='source_name',
        ),
        migrations.AddField(
            model_name='advertisementfile',
            name='origin_name',
            field=models.CharField(blank=True),
        ),
    ]
