# Generated by Django 4.2.6 on 2023-12-02 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_remove_advertisementfile_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementfile',
            name='user',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.PROTECT, related_name='advertisementfile_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
