# Generated by Django 4.2.6 on 2024-02-01 09:10

import ads.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0005_rename_trimeseter_courseteacherstudygroup_trimester'),
        ('ads', '0006_advertisementfile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['id'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='advertisementfile',
            options={'ordering': ['advertisement'], 'verbose_name': 'Файл объявления', 'verbose_name_plural': 'Файлы объявлений'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='body',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='groups',
            field=models.ManyToManyField(related_name='advertisement_studygroup', to='study.studygroup', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisement_user', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='advertisementfile',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_file', to='ads.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='advertisementfile',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='advertisementfile',
            name='file',
            field=models.FileField(upload_to=ads.models.advertisement_file_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='advertisementfile',
            name='origin_name',
            field=models.CharField(blank=True, verbose_name='Оригинальное название файла'),
        ),
        migrations.AlterField(
            model_name='advertisementfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisementfile_user', to=settings.AUTH_USER_MODEL, verbose_name='Владелец файла'),
        ),
    ]
