# Generated by Django 4.2.6 on 2023-11-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('level_of_higher_education', models.CharField(choices=[('BA', 'Бакалавриат'), ('SP', 'Специалитет'), ('MA', 'Магистратура'), ('AS', 'Аспирантура')], max_length=2)),
                ('study_period_months', models.PositiveSmallIntegerField()),
                ('form_of_study', models.CharField(choices=[('INTO', 'Очное'), ('EXTR', 'Заочное'), ('EVEN', 'Очно-заочное')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciality_cathedra', to='university.cathedra')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('house', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('number', 'house', 'floor')},
            },
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cathedra_faculty', to='university.faculty'),
        ),
    ]
