# Generated by Django 4.2.6 on 2024-02-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathedra',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cathedra_faculty', to='university.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.PositiveSmallIntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='house',
            field=models.PositiveSmallIntegerField(verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.CharField(max_length=150, verbose_name='Номер аудитории'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='cathedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciality_cathedra', to='university.cathedra', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(max_length=150, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='form_of_study',
            field=models.CharField(choices=[('INTO', 'Очное'), ('EXTR', 'Заочное'), ('EVEN', 'Очно-заочное')], max_length=4, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='level_of_higher_education',
            field=models.CharField(choices=[('BA', 'Бакалавриат'), ('SP', 'Специалитет'), ('MA', 'Магистратура'), ('AS', 'Аспирантура')], max_length=2, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='study_period_months',
            field=models.PositiveSmallIntegerField(verbose_name='Период обучения(мес.)'),
        ),
    ]
