# Generated by Django 4.2.6 on 2023-11-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('study', '0001_initial'),
        ('users', '0002_contacttype_personrole_teacher_student_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student_studygroup', to='study.studygroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='cathedra',
            field=models.ManyToManyField(related_name='teacher_cathedra', to='university.cathedra'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teacher_courses', to='study.course'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'study_group')},
        ),
    ]
