# Generated by Django 4.2.6 on 2023-11-29 14:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_study_group_teacher_cathedra_teacher_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_photo_directory_path),
        ),
    ]
