# Generated by Django 4.2.6 on 2023-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_rename_trimeseter_courseteacherstudygroup_trimester'),
        ('university', '0001_initial'),
        ('users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cathedra',
            field=models.ManyToManyField(blank=True, related_name='teacher_cathedra', to='university.cathedra'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teacher_courses', to='study.course'),
        ),
    ]
