# Generated by Django 4.2.6 on 2023-11-29 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('cr', 'Создана'), ('pr', 'В обработке'), ('re', 'Готова'), ('is', 'Выдана'), ('ca', 'Отменена')], max_length=2)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_certificatetype', to='certificate.certificatetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_user', to=settings.AUTH_USER_MODEL)),
                ('user_give', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_usergive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
