# Generated by Django 4.2.6 on 2023-12-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_photo'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacherStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_course', to='study.studyplancourses')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_studygroup', to='study.studygroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_teacher', to='users.teacher')),
            ],
        ),
    ]
