# Generated by Django 4.2.6 on 2023-12-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_courseteacherstudygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacherstudygroup',
            name='trimeseter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_trimester', to='study.trimester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseteacherstudygroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_course', to='study.course'),
        ),
    ]
