# Generated by Django 4.2.6 on 2023-12-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_courseteacherstudygroup_trimeseter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacherstudygroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_course', to='study.studyplancourses'),
        ),
    ]
