# Generated by Django 4.2.6 on 2024-02-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teacher_cathedra_alter_teacher_courses'),
        ('university', '0002_alter_cathedra_options_alter_classroom_options_and_more'),
        ('study', '0005_rename_trimeseter_courseteacherstudygroup_trimester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterModelOptions(
            name='controlmeasure',
            options={'verbose_name': 'Контрольное мероприятие', 'verbose_name_plural': 'Контрольные мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='controlmeasurescore',
            options={'verbose_name': 'Оценка за контрольное мероприятие', 'verbose_name_plural': 'Оценки за контрольные мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursescore',
            options={'verbose_name': 'Итоговая оценка', 'verbose_name_plural': 'Итоговые оценки'},
        ),
        migrations.AlterModelOptions(
            name='courseteacherstudygroup',
            options={'verbose_name': 'Курс, преподаватель, учебная группа', 'verbose_name_plural': 'Курсы, преподаватели, учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='studygroup',
            options={'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='studyplancourses',
            options={'verbose_name': 'Курс и учебный план', 'verbose_name_plural': 'Курсы и учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='trimester',
            options={'verbose_name': 'Триместр', 'verbose_name_plural': 'Триместры'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_pair', to='study.timetable', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='users.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_teacher', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursecontrolmeasure_course', to='study.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='max_score',
            field=models.FloatField(verbose_name='Максимальный балл'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='min_score',
            field=models.FloatField(verbose_name='Минимальный балл'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Порядок контрольной точки'),
        ),
        migrations.AlterField(
            model_name='controlmeasurescore',
            name='control_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlmeasurescore_controlmeasure', to='study.controlmeasure', verbose_name='Контрольное мероприятие'),
        ),
        migrations.AlterField(
            model_name='controlmeasurescore',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='controlmeasurescore',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='controlmeasurescore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlmeasurescore_student', to='users.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='controlmeasurescore',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlmeasurescore_teacher', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom_worktime',
            field=models.PositiveSmallIntegerField(verbose_name='Количество ауд. часов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=150, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='course',
            name='count_of_laboratory_pairs',
            field=models.PositiveSmallIntegerField(verbose_name='Количество лаб. пар'),
        ),
        migrations.AlterField(
            model_name='course',
            name='count_of_lectures_pairs',
            field=models.PositiveSmallIntegerField(verbose_name='Количество лек. пар'),
        ),
        migrations.AlterField(
            model_name='course',
            name='count_of_practies_pairs',
            field=models.PositiveSmallIntegerField(verbose_name='Количество прак. пар'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='independent_worktime',
            field=models.PositiveSmallIntegerField(verbose_name='Количество сам. часов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(related_name='course_teacher', to='users.teacher', verbose_name='Владельцы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcourse_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='Номер субкурса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_of_course',
            field=models.CharField(choices=[('STUDY_PRAC', 'Практика'), ('DISCIPLINE', 'Дисциплина'), ('STUDY_PRAC', 'Учебная практика'), ('PROD_PRAC', 'Производственная практика'), ('COURSE', 'Курсовая работа'), ('GROUP', 'Групповая работа'), ('NIRS', 'Научно-исследовательская работа'), ('GOS_EX', 'Государственный экзамен'), ('DIPLOM', 'Квалификационная работа'), ('PHYS_CULT', 'Физическая культура')], max_length=10, verbose_name='Тип курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_of_mark',
            field=models.CharField(choices=[('ex', 'Экзамен'), ('za', 'Зачет')], max_length=2, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursescore_course', to='study.studyplancourses', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='score',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('OK', 'Зачет'), ('FA', 'Незачет'), ('NO', 'Не выставлено')], max_length=2, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursescore_student', to='users.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursescore_teacher', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='courseteacherstudygroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_course', to='study.studyplancourses', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseteacherstudygroup',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_studygroup', to='study.studygroup', verbose_name='Учебная группа'),
        ),
        migrations.AlterField(
            model_name='courseteacherstudygroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_teacher', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='courseteacherstudygroup',
            name='trimester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseteacherstudygroup_trimester', to='study.trimester', verbose_name='Триместр'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='begin_date',
            field=models.DateField(verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='code',
            field=models.CharField(max_length=150, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studygroup_studyplan', to='study.studyplan', verbose_name='Учебный план'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='code',
            field=models.CharField(max_length=150, unique=True, verbose_name='Код учебного плана'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studyplan_speciality', to='university.speciality', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='studyplancourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studyplancourses_course', to='study.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='studyplancourses',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studyplancourses_studyplan', to='study.studyplan', verbose_name='Учебный план'),
        ),
        migrations.AlterField(
            model_name='studyplancourses',
            name='trimester',
            field=models.PositiveSmallIntegerField(verbose_name='Триместр'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_classroom', to='university.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_course', to='study.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(verbose_name='Дата пары'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='groups',
            field=models.ManyToManyField(related_name='timetable_group', to='study.studygroup', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='index_pair',
            field=models.PositiveSmallIntegerField(verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='is_attendance',
            field=models.BooleanField(blank=True, default=None, verbose_name='Посещаемость'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_teacher', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='type_of_pair',
            field=models.CharField(choices=[('LE', 'Лекция'), ('PR', 'Практика'), ('LA', 'Лабораторная работа')], max_length=2, verbose_name='Тип пары'),
        ),
        migrations.AlterField(
            model_name='trimester',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='trimester',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='trimester',
            name='trimester',
            field=models.CharField(choices=[('1', 'Осенний'), ('2', 'Весенний'), ('3', 'Летний')], max_length=1, verbose_name='Триместр'),
        ),
    ]
